name: stomp_dart_client
homepage: https://github.com/blackhorse-one/stomp_dart
version: 2.1.1
description: Dart STOMP client for easy messaging interoperability. Build with flutter in mind, but should work for every dart application.
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  web: ^1.0.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  test: ^1.25.8
  lints: ^5.0.0
  stream_channel: ^2.1.2
